config/routes.rb
Tenthousandhours::Application.routes.draw do
  resources :entries
  resources :skills
  resource :profile
  devise_for :users
  root "home#index"
  

end

app/models/entry.rb
class Entry < ActiveRecord::Base

  default_scope order('created_at DESC')
  
  belongs_to :user
  belongs_to :skill

  validates :note, length: { maximum: 250 }
  validates :hours, numericality: { greater_than: 0 }

end

app/models/skill.rb
class Skill < ActiveRecord::Base
    has_many :entries
    has_many :users, through: :entries
    validates :name, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :skills, through: :entries
    has_many :entries
    

    attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
  validates :username, :uniqueness => { :case_sensitive => false }

    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  def show
    @user = current_user
    end
  
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  
  def index
    @entries = Entry.all(:order => "created_at DESC")
  end

  def show
    @entry = Entry.find params[:id]
  #rescue ActiveRecord::RecordNotFound
    #redirect_to new_entry_path
  end

  def new
    @entry = Entry.new
    @skills = Skill.all
  end

  def update
      @skills = Skill.all
      @entry = Entry.find params[:id]
      @entry.update safe_entry
      redirect_to @entry
     end

  def edit
    @entry = Entry.find params[:id]
    @skills = Skill.all
  end

  def create
    @skills = Skill.all
    @entry = current_user.entries.new safe_entry
    if @entry.save
      flash[:notice] = "You have added a new entry to your skillset"
      redirect_to @entry
    else
      render 'new'
    end
  end

  private
    def safe_entry
      params.require(:entry).permit(:hours, :note, :user_id, :skill_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @skills = Skill.all
    @entries = Entry.all
    @current_user = current_user
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    def show
        @users = User.all
        @skills = Skill.all
        @user = User.find params[:id]
        @skill = Skill.find params[:id]
    end

    def index
    end

    def edit
    end

    def update
    end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
before_action :authenticate_user!, only: [:new, :create]

    def index
        @skills = Skill.all
    end

    def show
        @skill = Skill.find params[:id]
        @entries = Entry.all
    #rescue ActiveRecord::RecordNotFound
        #flash[:alert] = "We don't have that skill in our system"
        #redirect_to root_path
    end

    def new
        @skill = Skill.new
    end

    def create
        @skill = Skill.new safe_skill
        if @skill.save
            flash[:notice] = "You have added a new skill to our system!"
            redirect_to @skill
        else
            render 'new'
    end
end
    private
    def safe_skill
        safe_skill = params.require(:skill).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/entries/edit.html.erb
<% if @entry.errors.any? %>
  <h2>There were errors editing your entry</h2>
  <ul>
    <% @entry.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<p></p>

<%= form_for @entry do |f| %>

<fieldset>
<legend>Edit your Entry</legend>
    <div class="form">
    <%= f.label :skill_id, "Select a Skill" %>
    <%= f.collection_select :skill_id, @skills, :id, :name %>
    </div><div class="form">
    <%= f.label :hours %>
    <%= f.text_field :hours %>
    </div><div class="form">
    <%= f.label :note %>
    <%= f.text_area :note %>
    </div>
</fieldset>
    <%= f.submit 'Update my Hours', :class => 'superbutton' %>
    <% end %>

app/views/entries/index.html.erb
<h1>Index of Entries</h1>

<%= render "layouts/listentries" %>

app/views/entries/new.html.erb
<h1>Add Hours To Your Cumulative Skill</h1>

<% if @entry.errors.any? %>
  <h2>There were errors saving your entry</h2>
  <ul>
    <% @entry.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @entry do |f| %>

<fieldset>
<legend>New Entry</legend>
    <div class="form">
    <%= f.label :skill_id, "Select a Skill" %>
    <%= f.collection_select :skill_id, @skills, :id, :name %>
    </div><div class="form">
    <%= f.label :hours %>
    <%= f.text_field :hours %>
    </div><div class="form">
    <%= f.label :note %>
    <%= f.text_area :note %>
    </div>
</fieldset>
    <%= f.submit 'Add my Hours', :class => 'superbutton' %>
    <% end %>

app/views/entries/show.html.erb
<h1><%= link_to @entry.skill.name, skill_path(:id => @entry.skill_id) %></h1>
<h2><%= @entry.hours %> hours</h2>
<h3><%= @entry.note %></h3>
<% if @entry.user.username? %>
<h3><%= link_to @entry.user.username, profile_path(:id => @entry.user) %></h3>
<% else %>
<h3><%= link_to @entry.user.email, profile_path(:id => @entry.user) %></h3>
<% end %>
<% if @entry.user == current_user %>
<p><%= link_to "Edit this Entry", edit_entry_path %></p>
<% else %>
<% end %>

<div class="button"><%= link_to "Add Another Entry", new_entry_path %></div>
<p>Or, return to <%= link_to "Home Page", root_path %></p>

app/views/home/index.html.erb
<p class="center" padding-left="250px">get the skills to pay your bills</p>


<h1>Here's what other people are learning</h1>

<%= render "layouts/listentries" %>

app/views/layouts/_listentries.html.erb
<ul>
<% @entries.each do |entry| %>
  <li> 
  <% if entry.user == current_user %> 
  <%= entry.user.username %> <span class="tiny"><%= link_to "your profile", profile_path(:id => entry.user) %></span>
  <% else %>
  <%= link_to entry.user.username, profile_path(:id => entry.user) %>
  <% end %><br />
  <span class="sortabig"><%= link_to entry.skill.name, skill_path(:id => entry.skill) %></span>   <i><%= entry.hours %> hours </i><br />
    <%= link_to entry.note, entry_path(:id => entry) %> 
    <hr>
    </li>
<% end %>
</ul>

<% if user_signed_in? %>
  <div class="button"><%= link_to "Add a New Entry", new_entry_path %></div>
<% else %>
  <div><p><%= link_to "Sign in to Add an Entry", new_user_session_path %> || <%= link_to "See All Skills", skills_path %></p></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= favicon_link_tag %>
<head>
  <title>Ten Thousand Hours</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="page_container">
<div class="nav">
  <div class="logotype first">
    <%= link_to "tenTHOUSANDhours", root_path %> 
  </div>

    <% if user_signed_in? %>
    <div class="second"><p><%= link_to "All Skills", skills_path %> 
    || <b><%= link_to "Add a New Entry", new_entry_path %></b> 
    || Welcome, <%= link_to current_user.username , profile_path(id:current_user) %>! 
    || <%= link_to "Sign Me Out", destroy_user_session_path, method: :delete %>
    </p></div>
    <% else %>
    <div class="second"><%= link_to "Sign In", new_user_session_path %> | <%= link_to "New User", new_user_registration_path %></div>
    <% end %>
    
    </div>



    <% if notice %>
    <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert"><%= alert %></p>
      <% end %>
      <div id="maincontainer">
<%= yield %>
</div>
</div>
</body>
</html>

app/views/profiles/show.html.erb
<h1>Profile Page</h1>

<h3>Email: <%= @user.email %></h3>
<% if @user.username? %>
<h3>Username: <b><%= @user.username %></b></h3>
<% end %>

<h2>Special Skills</h2>
<% @user.skills.uniq.each do |skill| %>
<!-- @user.skills.distinct.pluck(:name).each -->
<ul>
<li>
<p class="prettybig"><%= link_to skill.name, skill_path(:id => skill) %>
<span class="secondspan">total hours: <%= skill.entries.sum(:hours) %></span></p>

<% if (skill.entries.sum(:hours) >= 100) %>
    <% if @user == current_user %>
    <div class="award">You have earned the rank of<br /> JOURNEYMAN! <br />for <%= skill.name %></div>
    <% else %>
    <div class="award"><%= @user.username %> has earned the rank of<br /> JOURNEYMAN! <br />for <%= skill.name %></div>
    <% end %>

<% elsif (skill.entries.sum(:hours) >= 50)%>
    <% if @user == current_user %>
    <div class="award">You have earned the rank of<br /> BEGINNER'S MIND! <br />for <%= skill.name %></div>
    <% else %>
    <div class="award"><%= @user.username %> has earned the rank of<br /> BEGINNER'S MIND! <br />for <%= skill.name %></div>
    <% end %>

<% elsif (skill.entries.sum(:hours) >= 10)%>
    <% if @user == current_user %>
    <div class="award">You have earned the rank of<br /> NOVICE! <br />for <%= skill.name %></div>
    <% else %>
    <div class="award"><%= @user.username %> has earned the rank of<br /> NOVICE! <br />for <%= skill.name %></div>
    <% end %>
<% else %>
<% end %>
</li>
</ul>
<% end %>
<div class="button"><%= link_to "Add a New Entry", new_entry_path %></div>
<p>Or, you can <%= link_to "Add a New Skill to the Database", new_skill_path %></p>

<!-- for doing sum of hours
 @cart.items.joins(:product).sum("products.price") -->

app/views/skills/index.html.erb
<h1>All Available Skills</h1>

<ul>
<% @skills.each do |skill| %>
    <li><%= link_to skill.name, skill %></li>
<% end %>
</ul>

<div class="button">
<%= link_to "Add a Skill", new_skill_path %>
</div>

app/views/skills/new.html.erb
<h1>Add a New Skill to our Database</h1>

<%= form_for @skill do |f| %>
<fieldset>
<legend>New Skill</legend>
    <div class="form">
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div><div class="form">
    <%= f.label :description %>
    <%= f.text_area :description %>
    </div>
</fieldset>
    <%= f.submit 'Add this Skill', :class => 'superbutton' %>
    <% end %>

app/views/skills/show.html.erb
<h1><%= @skill.name %></h1>
<h2><%= @skill.description %></h2>

<ul>
<% @skill.entries.each do |entry| %>
<li> 
  <% if entry.user == current_user %> 
  <%= entry.user.username %> <span class="tiny"><%= link_to "your profile", profile_path(:id => entry.user) %></span>
  <% else %>
  <%= link_to entry.user.username, profile_path(:id => entry.user) %>
  <% end %><br />
  <%= link_to entry.skill.name, skill_path(:id => entry.skill) %>  <i>hours: <%= entry.hours %></i><br />
    <%= link_to entry.note, entry_path(:id => entry) %> 
    <hr>
    </li>
<% end %>
</ul>


<div class="button">
<%= link_to "Add A Skill to the Database", new_skill_path %></div>

<p><%= link_to "See all Skills", skills_path %> || <%= link_to "Home Page", root_path %></p>